### ISSUE TITLE
add optional resists to boss guide

### ISSUE THREAD

**Issue by seiyria** [seiyria/anamnesiac#218]
for example, michael: Resists: Fire (90%), Lightning (50%), Wind (50%), Earth (50%), Light (50%), Dark (50%)

it should support the same format as weaknesses - element, status, plain

this should also be propagated to the discord bot.

**Comment by GitDaskar** [comment]
This enhancement doesn't seem to be propagating to the discord bot.

**Comment by seiyria** [comment]
that's tracked separately https://github.com/seiyria/discord-anamnesiac/issues/15
