### ISSUE TITLE
true: all displays as (Party) in discord bot, but shows (Allies) in app

### ISSUE THREAD

**Issue by GitDaskar** [seiyria/anamnesiac#491]
Expected behavior: Should show as (Party) in the app.

**Comment by seiyria** [comment]
I think this is resolved as of today. Please confirm and let me know if not.

**Comment by GitDaskar** [comment]
I did not confirm this issue was resolved when the ticket was closed, but the app currently shows (Allies) instead of (Party).  It's incorrectly showing this on Talents and Rushes for both GL and JP on several characters.

**Comment by GitDaskar** [comment]
Can someone else check this?

**Comment by GitDaskar** [comment]
This is resolved.
