### ISSUE TITLE
some items need separate lb factors

### ISSUE THREAD

**Issue by seiyria** [seiyria/anamnesiac#78]
add a "limitBreakSecondFactor" and "limitBreakFirstFactor"

add these factors instead to the actual factor object. display it inline in the factor box.

use the "weapon level" icons and say "Unlocked at <icon>" above the factor, probably italicized

**Comment by Coy47** [comment]
Slayer of Divine Beings lb factors at 3 / 4 / 5
Slayer of Divine Being II lb factors at 1 / 3

**Comment by seiyria** [comment]
I've taken care of shiny rupture I/II and divine beings I/II (as well as reformatted the entire data set). If anything else comes up, feel free to send a PR!
